### ISSUE TITLE
EncryptionKey in HMAC

### ISSUE THREAD

**Issue by dhcgn** [RNCryptor/RNCryptor-Spec#7]
Why is the EncryptionKey not part of the HMAC?
So if the HAMC is checked a wrong EncryptionKey would prevent the encryption.

```
HMAC = HMAC(Header || Ciphertext, HMACKey, SHA-256)
HMAC = HMAC(Header || Ciphertext || EncryptionKey, HMACKey, SHA-256)
```

**Comment by dhcgn** [comment]
I just saw, that in the new version, _validator_ is introduced for this purpose.

> validator (16 bytes): used to determine if password is correct

**Comment by chesstrian** [comment]
@dhcgn Totally right, will check to implement v4.0, only v3.0 is currently implemented.
