### ISSUE TITLE
Double key derivation is attacker friendly

### ISSUE THREAD

**Issue by ecki** [RNCryptor/RNCryptor-Spec#9]
Since you need to run password derivation two times (HMAC and encryption key) the number of acceptable iterations must be half the number which would be possible. It would be better to either derive both keys from a single PBKDF2 procedure (allows key expansion) or from hash-deriving two keys from a single PBKDF2 master secret. The later has the additional advantage that the two different keys would contain a usage specific identifier (and not only the semantic free salt)

**Comment by rnapier** [comment]
See the v4 spec, which uses a more efficient HKDF expansion.

I wouldn't consider this attacker friendly; 10k iterations is an appropriate value. The problem is that it wastes time for no added security.

**Comment by rnapier** [comment]
(Note that there are no implementations of the v4 spec currently. You're reviewing the correct one; v3.)

**Comment by ecki** [comment]
Oh ok, missed the draft. I agree it addresses my issues. 

BTW i would use 10^(rounds+2) (not less than 1000 rounds) to not waste bits.
For the validation 32bits are enough.
